# Generated by Django 4.2.5 on 2023-09-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myjsonModel", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="stocks",),
    ]
